#!/usr/bin/ruby
# linux系统安装 ag ,可以利用本脚本在固定的文件下搜索文章,
# 本地博客检索使用
re = `ag #{ARGV[0]} ~/blog/`.split("\n")
title = ""
out = false
 re.each do |r|
   info =  r.split(/:[0-9]{1,100}:/)
   if title != info[0]
     title = info[0]
     puts "\n\e[1;40;37m#{info[0]}\e[0m"
   end
   r =~ /:[0-9]{1,100}:/
   printf "\t\e[36m#{$&.gsub(/:/,"")}\e[0m "
   info[1] =~ /#{ARGV[0]}/i
   info[1].gsub!(/#{ARGV[0]}/i,"\e[41m#{$&}\e[0m")
   printf"#{info[1]}\n"
 end
